### ISSUE TITLE
Migrate to Riot 3.0.0

### ISSUE THREAD

**Issue by syuilo** [syuilo/misskey-web#79]
https://github.com/riot/riot/issues/1694

* [x] `name`の代わりに`ref`を使う
* [ ] `ref`が付いた要素には`@refs.`でアクセスする
* [ ] `e.prevent-default!`を付ける

バグ？
* `virtual`がレンダリングされている
* タグの属性に null を渡すと "" になる

https://github.com/riot/riot/issues/2082
https://github.com/riot/riot/issues/2081
https://github.com/riot/riot/issues/2080

**Comment by syuilo** [comment]
スタイルも、デフォルトで scoped になったっぽいのでそこも要修正
